---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spoonythings-app
  labels:
    app: spoonythings-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spoonythings-app
  template:
    metadata:
      labels:
        app: spoonythings-app
    spec:
      containers:
      - name: spoonythings-container
        image: 913524947374.dkr.ecr.us-east-1.amazonaws.com/springboot-app:latest
        ports:
        - containerPort: 3000
...
